name: lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint
